version: '2'

services:
  adapter:
    build:
      context: ./
      dockerfile: dockerfile-gtkusr
    ports: 
      - "5600:4021"
    links:
      - keycloak
    environment:
      - KEYCLOAK_ADDRESS=keycloak
      - KEYCLOAK_PORT=5801
      - KEYCLOAK_PATH=auth
      - SONATA_REALM=sonata
      - CLIENT_NAME=adapter
    container_name: sonata-gtkusr
  keycloak:
    build:
      context: ./
      dockerfile: dockerfile-keycloak
    ports:
      - "5601:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    links:
      - adapter
    container_name: sonata-keycloak    
